### ISSUE TITLE
[Bug]: Yung's Better Stronghold ( end portal ) contains outdated structure files 

### ISSUE THREAD

**Issue by GamingHQ** [dr3ams/Life-in-the-village-3#110]
### General Info

- [X] I didn't add any mods
- [X] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

2.9

### Describe your issue

Yung's Better Stronghold contains outdated structure files that could cause world gen freezes/lag. 

### Steps to reproduce the issue

None. Randomly roaming on the map will cause the freezes during Worldgen. This causes significant drop/freeze moments when roaming

### Additional Information

The usual error logs from Modernfix.

Structure betterdungeons:skeleton_dungeon/arches/arch_8 is being run through DFU (hash 7221c6512c872d24d97a0273ab0a76e04caaef4b866068d9d268be23cc447070), this will cause launch time delays

My report: https://github.com/YUNG-GANG/YUNGs-Better-Strongholds/issues/89

**Comment by Gunner76th** [comment]
Please provide logs files or citations from Yungs that supports this please. Without documentation to verify the statement, as well as a way to fix it, there is little we can do.

**Comment by GamingHQ** [comment]
> Please provide logs files or citations from Yungs that supports this please. Without documentation to verify the statement, as well as a way to fix it, there is little we can do.

Please, stay out of my bug reports if you are not a staff member.

**Comment by Gunner76th** [comment]
> > Please provide logs files or citations from Yungs that supports this please. Without documentation to verify the statement, as well as a way to fix it, there is little we can do.
> 
> Please, stay out of my bug reports if you are not a staff member.

I am a staff member for Dreams and have been since about 2019. And even if I wasn't,  my previous statement is still true.

**Comment by GamingHQ** [comment]
https://pastebin.com/m9VsL36b

**Comment by Gunner76th** [comment]
I see in the log snippet that it says that its running through a DFU, and that it might cause launch delays, but I am not seeing or understanding where it is showing that Yungs is using outdated structure files. 

After looking into the mod file itself, and where the structure data is stored, this isnt an issue we can address or fix. The structure data is stored inside the jar file itself in the "YungsBetterStrongholds-1.19.2-Forge-3.2.0.jar\data\betterstrongholds\structures\"

This is an issue that would need to be addressed by the Yung's author. As such, this issue and issue https://github.com/dr3ams/Life-in-the-village-3/issues/109 can both be closed as the issue is not with LITV 3 itself, but one of the mods therein. Removing the Yung's mods is the only way we would be able to address this issue, and that most likely is not something that would be happening.

**Comment by GamingHQ** [comment]
"Removing the Yung's mods is the only way we would be able to address this issue, and that most likely is not something that would be happening."

That's pretty disappointing to read that you guys rely on other mods, for a mod pack to work. I would at least have tried to find something else as a temporary replacement. I mean, I doubt these buildings have anything quest or storyline-related content in them and i doubt there would be only 1 mod that alters the stronghold area.

I wish you guys good luck with the modpack. We will be de-installing it and searching for something else. The modpack is barely playable in this state if several users are roaming around at the same time. Please, change the information on the modpack page that this modpack should be seen "as-is" to prevent further confusion if a modpack works or not.
