### ISSUE TITLE
[Bug]: Missing Quark Recipe's ( Chests )

### ISSUE THREAD

**Issue by GamingHQ** [dr3ams/Life-in-the-village-3#111]
### General Info

- [X] I didn't add any mods
- [ ] I can reproduce this issue consistently in single-player
- [X] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [X] I am using the latest version of the modpack

### Your launcher

CurseForge

### Modpack version

2.9

### Describe your issue

It appears that several items are not within the pack active. While we get a netherrite brick chest as a reward from a quest, there is not a single way to actually craft one. 

### Steps to reproduce the issue

Checked the JEI, no success on finding the chests.
Checked in creative mode, no success on finding these chests. 

### Additional Information

no error has been shown.

**Comment by Gunner76th** [comment]
You are playing a modpack that is using custom recipes and modified configs. The quark chests appear to be disabled in the modpack, most likely since the modpack is using Sophisticated Storage. This is further confirmed by looking at line 113 of the quark_common.toml file that states that:

	"Variant Chests" = false

Quarks chests being missing is not a bug, and thus this is not an issue, the game is working as intended. 

This ticket can be closed.

**Comment by GamingHQ** [comment]
> You are playing a modpack that is using custom recipes and modified configs. The quark chests appear to be disabled in the modpack, most likely since the modpack is using Sophisticated Storage. This is further confirmed by looking at line 113 of the quark_common.toml file that states that:
> 
> ```
> "Variant Chests" = false
> ```
> 
> Quarks chests being missing is not a bug, and thus this is not an issue, the game is working as intended.
> 
> This ticket can be closed.

Since when are you a staff member?

**Comment by Gunner76th** [comment]
I am a staff member for Dreams and have been since about 2019.

Regardless of it someone is a staff member or not,  they are allowed to reply to bug reports when the information they are providing is accurate. Also we have people in the modpack dev teams who are not "staff" for the community and who are not listed on curseforge or github.

**Comment by GamingHQ** [comment]
Welp, that's pretty confusing for those who would like to do a proper report to the mod pack creator or contributor. Does github have no "staff tags" or something by any chance? ( don't know if they have it, just asking )
