### ISSUE TITLE
[Bug]: Can't install modpack

### ISSUE THREAD

**Issue by romaust** [dr3ams/Life-in-the-village-3#33]
### General Info

- [ ] I didn't added any mods
- [ ] I can reproduce this issue consistently in single-player
- [ ] I can reproduce this issue consistently in multi-player
- [X] I have searched for this issue previously and it was either (1) not previously reported, or (2) previously fixed and I am having the same problem.
- [ ] I am crashing and can provide my crash report(s)
- [ ] I am using the latest version of the modpack

### Your launcher

Curceforge, MultiMC

### Modpack version

1.8, 1.7, 1.6, 1.0

### Describe your issue

Imposible to install modpack.
MultiMC resolving mod IDs, then show error message "Unable to resolve mod IDs: Some mod ID resolving tasks failed."
Curceforge cancel instalation after applying patches, and created folder.

### Additional Information

There is no logs, because i cant install modpack

**Comment by DoctorMage** [comment]
Multimc dropped curseforge supprot ages ago due to api changes  https://github.com/MultiMC/Launcher/wiki/Manually-importing-modpacks
just installed 1.6 versions 

so an issue on your end can try reinstalling curseforge or repairing installation
![image](https://user-images.githubusercontent.com/85318453/216990106-44963f4a-43b8-4de4-a473-e8065354c331.png)

**Comment by romaust** [comment]
Ok, now it's good. But it's a shame for MultiMC
